<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TypeSafe.AI/TypeSafe.AI.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>
</Project>
